# .github/workflows/build-publish-electron.yml

name: Build and Publish Electron App (Cross-Platform)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version || '20.x' }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version || '20.x' }}-

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS (if applicable)
        run: npm run build:css

      - name: Build and Publish App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
